import type { Collection } from "tinacms";
import Contact from "./contact";
import Courses from "./courses";
import Disclaimer from "./disclaimer";
import Formations from "./formations";
import Header from "./header";
import Opinions from "./opinions";
import Pages from "./pages";
import Prices from "./prices";
import Services from "./services";
import SocialMedia from "./socialMedia";
import SocialMediaBis from "./socialMediaBis";

export const contactCollection: Collection = Contact;
export const coursesCollection: Collection = Courses;
export const pagesCollection: Collection = Pages;
export const opinionsCollection: Collection = Opinions;
export const servicesCollection: Collection = Services;
export const socialMediaCollection: Collection = SocialMedia;
export const socialMediaBisCollection: Collection = SocialMediaBis;
export const headerCollection: Collection = Header;
export const disclaimerCollection: Collection = Disclaimer;
export const pricesCollection: Collection = Prices;
export const formationsCollection: Collection = Formations;
