import columnSection from "./columnSection";
import contactSection from "./contactSection";
import disclaimerSection from "./disclaimerSection";
import heroSection from "./heroSection";
import introductionSection from "./introductionSection";
import opinionsSection from "./opinionsSection";
import pricesSection from "./pricesSection";
import servicesSection from "./servicesSection";
import splittedSection from "./splittedSection";
import textSection from "./textSection";

export const columnSectionType = columnSection;
export const contactSectionType = contactSection;
export const disclaimerSectionType = disclaimerSection;
export const heroSectionType = heroSection;
export const introductionSectionType = introductionSection;
export const opinionsSectionType = opinionsSection;
export const pricesSectionType = pricesSection;
export const servicesSectionType = servicesSection;
export const splittedSectionType = splittedSection;
export const textSectionType = textSection;
