import bannerSection from "./bannerSection";
import cardsSection from "./cardsSection";
import columnSection from "./columnSection";
import contactSection from "./contactSection";
import coursesSection from "./coursesSection";
import disclaimerSection from "./disclaimerSection";
import flowerSection from "./flowerSection";
import formationsSection from "./formationsSection";
import heroSection from "./heroSection";
import introductionSection from "./introductionSection";
import opinionsSection from "./opinionsSection";
import pricesSection from "./pricesSection";
import servicesSection from "./servicesSection";
import splittedSection from "./splittedSection";
import textSection from "./textSection";

export const bannerSectionType = bannerSection;
export const cardsSectionType = cardsSection;
export const columnSectionType = columnSection;
export const contactSectionType = contactSection;
export const coursesSectionType = coursesSection;
export const disclaimerSectionType = disclaimerSection;
export const flowerSectionType = flowerSection;
export const formationsSectionType = formationsSection;
export const heroSectionType = heroSection;
export const introductionSectionType = introductionSection;
export const opinionsSectionType = opinionsSection;
export const pricesSectionType = pricesSection;
export const servicesSectionType = servicesSection;
export const splittedSectionType = splittedSection;
export const textSectionType = textSection;
