import column from "./columnSection";
import contact from "./contact";
import disclaimer from "./disclaimer";
import flower from "./flowerSection";
import hero from "./hero";
import introduction from "./introduction";
import opinions from "./opinions";
import prices from "./prices";
import services from "./services";
import splitted from "./splittedSection";
import text from "./text";

export const columnSection = column;
export const contactSection = contact;
export const diclaimerSection = disclaimer;
export const flowerSection = flower;
export const heroSection = hero;
export const introductionSection = introduction;
export const opinionsSection = opinions;
export const pricesSection = prices;
export const servicesSection = services;
export const splittedSection = splitted;
export const textSection = text;
