backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Réseaux sociaux"
    name: "socialMediaBis"
    files:
      - label: "Réseaux sociaux"
        name: "socialMedia"
        file: "src/content/socialMedia/socialMedia.md"
        fields:
          - {label: "Facebook", name: "facebook", widget: "string"}
          - {label: "Instagram", name: "instagram", widget: "string"}
          - {label: "Linkedin", name: "linkedin", widget: "string"}
  - label: "Menu"
    name: "header"
    create: false
    delete: false
    files:
      - label: "Menu"
        name: "header"
        file: "src/content/header/header.md"
        fields:
          - label: "Logo"
            name: "logo"
            widget: "image"
            allow_multiple: false
            choose_url: false
          - label: "Pages"
            name: "pages"
            widget: "relation"
            collection: "pages"
            value_field: "{{slug}}"
            display_fields: ["title"]
            search_fields: ["title"]
            multiple: true
  - label: "Pages"
    name: "pages"
    folder: "src/content/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
